version: '3'


services:
  mysql:
    container_name: "mysql"
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "redditclone"
    ports:
      - '3306:3306'
    volumes:
      - "../scripts:/docker-entrypoint-initdb.d/"
      - "../tmp/mysql:/var/lib/mysql"

  redis:
    container_name: "redis"
    image: redis  
    ports:
      - '6379:6379'

  mongodb:
    container_name: "mongodb"
    image: 'mongo:5'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - '27017:27017'
    volumes:
      - "../tmp/mongodb:/data/db"
    
